### ISSUE TITLE
Double logging entries and one visible for Player

### ISSUE THREAD

**Issue by veithflo** [jessev14/dnd5e-character-monitor#1]
Hi there,

Pictures say more than thousand words ...

![grafik](https://user-images.githubusercontent.com/32668369/144712072-81907c8c-b846-4b09-a8c4-8cc6cf763f21.png)

![grafik](https://user-images.githubusercontent.com/32668369/144712081-4fa7ce02-b046-4b1c-a1fa-311d1c1e7665.png)

![grafik](https://user-images.githubusercontent.com/32668369/144712084-f896494b-2161-402c-aaf8-5db37c82bc5a.png)

![grafik](https://user-images.githubusercontent.com/32668369/144712086-42be01a4-1265-446e-b975-6c318cc702f6.png)

Using FVTT 0.8.9, most recent DND5e and versions of your modules.

**Comment by jessev14** [comment]
Thanks for the heads up! Update the module to get the fix, let me know if any other issues come up.

**Comment by veithflo** [comment]
Thank you. Issue is resolved.
