### ISSUE TITLE
[Feature Request] Monitor when a PC changes skill proficiencies.

### ISSUE THREAD

**Issue by AzulianCamel** [jessev14/dnd5e-character-monitor#10]
I would find it so incredibly helpful if there was support for monitoring the skill proficiencies for players. For example, it could be if they gain the proficiency or increase it to expertise/jack of all trades. Thank you for your incredible work so far!

**Comment by jessev14** [comment]
This module was developed as part of a commission, so unfortunately I'm not able to add new features in my free time.
I'm happy to merge pull requests if you'd like to implement the feature yourself or you can reach out to me on Discord to discuss funding the feature. `enso#0361`
