### ISSUE TITLE
[Feature Request] Show old resource value when it is changed

### ISSUE THREAD

**Issue by funwithfondue** [jessev14/dnd5e-character-monitor#11]
It would be nice to see in the information when a resource value is changed, which value it was changed from. For example, if someone changes their gold amount from 40gp to 20gp it would show something like "Player Character Name | 40gp -> 20gp"

Thanks a lot for this module! It's very helpful!

**Comment by jessev14** [comment]
That's a good idea! Unfortunately this module was developed on a commission so I don't have the ability to work on it in my free time. However, I'd be happy to merge a pull request if you'd like to implement the feature yourself, or you can reach out to me on Discord to discuss funding the feature: `enso#0361`.

**Comment by funwithfondue** [comment]
Very fair! Thank you nonetheless for the tool!

**Comment by jessev14** [comment]
A new commission was opened to fund this feature. You can enable it in the module settings after updating to version 1.6.2.

**Comment by funwithfondue** [comment]
Thank you very much! Just tried it and this is perfect!
