### ISSUE TITLE
Doesn't update spell slots when a character uses a spell

### ISSUE THREAD

**Issue by GambetTV** [jessev14/dnd5e-character-monitor#14]
Seems like an oversight, but it might be a bug. When a character uses a spell, this doesn't show an update to their spell slots. The change does occur since it's automated to the 5e system, but your module doesn't seem to pick it up. If I manually change the values of the spell slots, then it works as intended.

**Comment by jessev14** [comment]
The readme states that only changes to the character sheet are tracked.
