### ISSUE TITLE
Monitor currency (feature request)

### ISSUE THREAD

**Issue by tigator** [jessev14/dnd5e-character-monitor#15]
This module is great for tracking changes on character sheets.  One problem my group commonly has is that they can't remember if they made changes to their money or not, and as the GM I don't have a clue whether they did.  Would it be possible to track changes in currency also?

**Comment by jessev14** [comment]
This should already be a feature. You might have to enable it in the module settings.

**Comment by tigator** [comment]
Sorry for delayed response.  You're correct, it is of course already a feature - I didn't have it because the latest version available via FoundryVTT's module search is 1.2.3, and that's how I installed it, but of course the latest version is 1.6.2, which I got via updating.  I assumed I'd already have the latest version upon a fresh install, not that I'd need to update right away.

So at any rate thank you!
