### ISSUE TITLE
Change font color (feature request)

### ISSUE THREAD

**Issue by jorgecomas** [jessev14/dnd5e-character-monitor#16]
Thanks for this great module. 
I'd love it if it were possible to change the font color of the messages this module outputs. I use other modules to change the background color of messages, and the current white font doesn't play along nicely. 
Thanks

**Comment by jessev14** [comment]
```
This module was funded by a commission, and unfortunately I don't have the means to develop modules in my free time.
If you'd like to implement this feature yourself I'd be happy to merge a pull request.
Otherwise, if you'd like to fund this feature, you can reach out to me on Discord: enso#0361.
```

**Comment by jorgecomas** [comment]
Hi! Thanks for your quick response. It's just a tiny thing, I don't think it warrants reworking the module, and I am a complete noob when it comes to GitHub (I don't even know how to do a pull request). Anyway, I solved the issue for my use case by deleting line 14 and changing line 15 to "color: black" on dnd5e-character-monitor.css
Thanks again, this is a very useful module.
