### ISSUE TITLE
[Bug] Show Previous Values not Working for Attributes

### ISSUE THREAD

**Issue by brunocalado** [jessev14/dnd5e-character-monitor#18]
Hi.

Show Previous Values is not Working for Attributes. After change the actor sheet there is a chat message, but it don't show the Previous Values

![image](https://user-images.githubusercontent.com/4999783/177061381-a92a0075-9cb8-4481-a0cb-9ad69e9e1d10.png)

tks

**Comment by jessev14** [comment]
![image](https://user-images.githubusercontent.com/68755874/182857347-62a729ad-7ab4-4c1c-8900-9e9205829c62.png)
it was a bug with ability scores. fixed in 1.6.3
