### ISSUE TITLE
Spell cast monitor

### ISSUE THREAD

**Issue by Horozarai** [jessev14/dnd5e-character-monitor#2]
It would be super neat if I, as a GM, would be able to see if the spell cast isn't prepared.

I'm running a lot of One-Shots with random groups, and sadly I've found that not all is honorable about having the "right" spell prepared or not. I really find this sad, since they undermine the rest of the players who would have gotten a chance to think outside the box.

**Comment by jessev14** [comment]
I see the reasoning behind this feature, but it does go against my personal philosophy of "don't use technical solutions for player problems."

It also feels a bit out of the scope of this module, which is just meant to track changes and does not have anything to do with when an item/spell is used during gameplay.

I think such a feature would be better suited in a separate module. If you feel strongly about this, feel free to reach out Discord (`enso#0361`) and I'd be happy to discuss more.
