### ISSUE TITLE
Make it a different tab to track from & track gold

### ISSUE THREAD

**Issue by VaethConner** [jessev14/dnd5e-character-monitor#3]
![image](https://user-images.githubusercontent.com/47077661/147138326-1acd1ebe-c0ef-4678-ad41-2abdc49aea67.png)

A similar-esk module does this called "Damage log". It would help keep all of these messages in a good spot compared to scrolling up to check it.

Also tracking gold/money subtractions and additions would help immensely.

(Updating to latest foundry would also be great too!)

**Comment by jessev14** [comment]
I'll get on updating this for FoundryVTT v9, but since this module was a commission, I won't have the time to add new features or compatibility with other modules.
