### ISSUE TITLE
Newest release, setting for hp monitor does nothing and is always on

### ISSUE THREAD

**Issue by MotoMoto1234** [jessev14/dnd5e-character-monitor#41]
Health monitor is always on, specially problematic if you have other modules dealing with damage, its needless spam.

**Comment by Sayshal** [comment]
Seconding this.

**Comment by jessev14** [comment]
Version 2.0.3 of the module should fix this.

**Comment by Herzlos87** [comment]
I have a strange problem, if someone adds potions it doesn't mark it with the message in chat, same thing if he modifies his stat points like strength - dexterity etc etc, if instead he adds Gold Coins instead it gives me the message in chat, I redid a new world with the same modules, and there instead it warns me if the players have increased or decreased the potions? What am I doing wrong? the settings and the modules are the same.
