### ISSUE TITLE
Restore Previous Styling

### ISSUE THREAD

**Issue by Sayshal** [jessev14/dnd5e-character-monitor#42]
In previous Character Monitor versions, the height of the entry in chat was relative to the size of the test. Now it is 3-4x the size of the text and feels obtrusive. Please restore the previous size or add a setting to return this to previous state.

**Comment by 4cer** [comment]
Hard seconded. I'd suggest adding a style switch, something along the lines of "Make tracking chat messages compact".

In a similar vein, perhaps a toggle-able mechanism to compact subsequent messages for the same actor/token into a single change log could be added. This would be particularly great for saving space when spell preparation macros are used etc.
Additionally, for joined messages something like the details tag or any similar structure could be used, where the message lists change categories and expandable structure contains timestamped change messages in order. This should probably be a separate issue, however.

**Comment by 4cer** [comment]
@Sayshal as a quick and dirty workaround, if you feel like editing module contents, you could edit the stylesheet at:
`Data/modules/dnd5e-character-monitor/styles/dnd5e-character-monitor.css`
Making the following changes:

Line 20, replace:
`    margin: 2px;`
With:
`    margin: 0px;`

Line 21, replace:
`    padding: 2px;`
With:
`    padding: 0px;`

Note that this modification can be performed with FVTT running, all you need to do is refresh the page after saving (F5 in most browsers). All existing and future entries will change in accordance to the new values.
Keep in mind, you'll have to redo it by hand after every module update/re-installation.

<details>
  <summary>Before and after comparison</summary>
  
  ![obraz](https://github.com/user-attachments/assets/21130325-31dd-4fe9-bf3b-9ef0fa200f3f)

  The same set of messages captured in two states: prior to changes (left) and afterwards (right)
  
</details>

**Comment by Sayshal** [comment]
Yeah I set mine to this, I'm too stupid to get this to work on Custom CSS module so it's update-proof, but here's my code:
```css
div div.dnd5e-cm {
    text-shadow: -1px -1px 0 #000, 1px -1px 0 #000, -1px 1px 0 #000, 1px 1px 0 #000;
    color: white;
    font-size: 12px;
    margin: -7px;
    padding: -7px;
    text-align: center;
}

**Comment by RawrKrake** [comment]
I totally agree, I liked the old design better as well.

**Comment by jessev14** [comment]
I didn't really change the style of the text. It's always been based off the dnd5e system CSS. But I do agree the new style of the messages isn't great. I reduced the font size and padding on monitor messages. New update soon.

![image](https://github.com/user-attachments/assets/5b1eb5e6-049a-4e06-b9d0-d165cb946973)
