### ISSUE TITLE
Module does not work if I set that gm only sees messages

### ISSUE THREAD

**Issue by Herzlos87** [jessev14/dnd5e-character-monitor#43]
hi I have this problem, that is if I put gm read only messages the module doesn't work, while if I disable it everything works but the users see everything, what can I do?

**Comment by 4cer** [comment]
Seems in v12 'CONST.DOCUMENT_PERMISSION_LEVELS.OWNER', specifically 'CONST.DOCUMENT_PERMISSION_LEVELS' is no longer available. Now 'CONST.DOCUMENT_OWNERSHIP_LEVELS' must be used instead.

As a quick fix, @Herzlos87 is you feel like tinkering with your module scripts, you could go into the module files and modify the following script:
`Data/modules/dnd5e-character-monitor/scripts/dnd5e-character-monitor.js`

By changing line 355 from:
`        ? game.users.filter(u => item.parent.testUserPermission(u, CONST.DOCUMENT_OWNERSHIP_LEVELS.OWNER)).map(u => u.id)`
To:
`        ? game.users.filter(u => item.parent.testUserPermission(u, CONST.DOCUMENT_OWNERSHIP_LEVELS.OWNER)).map(u => u.id)`

On FVTT v12.331, DND5e 3.3.1 this fixes the tracking for: spell preparing, item quantity changes, HP changes, equipping/unequipping equipment, spell slots, feature uses, skill proficiency, sheet mode toggle.
Currency tracking worked prior to it as well, for reasons undefined.

**Comment by Herzlos87** [comment]
Thank you so much, you solved a problem for me

**Comment by Herzlos87** [comment]
Thank you so much, you solved a problem for me

**Comment by jessev14** [comment]
fix was merged
