### ISSUE TITLE
Error when items quantity are changed

### ISSUE THREAD

**Issue by Stonedtroll** [jessev14/dnd5e-character-monitor#45]
I know that Foundry v12 is not yet supported but I thought you might want to track.

![image](https://github.com/user-attachments/assets/98c885a0-5af1-4739-80c9-2e68d91f9599)

Foundry v12.331
D&D5e v3.3.1
D&D5e Character Monitor v2.0.3

**Comment by Bryn1701** [comment]
Also having the same issue. Also to double check version 2.0.2 says it was updated for v12 and D&D 5e version 3.3.1. Was curious if that was correct? Thanks in advance.

**Comment by jessev14** [comment]
this should be fixed in the next update
