### ISSUE TITLE
Is there a solution in sight?

### ISSUE THREAD

**Issue by DM-Kunz** [jessev14/dnd5e-character-monitor#47]
This module is very good, but since I updated the version to V12 it has been presenting several problems. It displays notifications every time someone opens/closes a spell, resource, etc. It also stops working when I enable the option to show notifications only to the GM.

There is also something that is not really a problem, but rather a personal preference, I prefer the more compact notifications as they were before, is there an easy way to change to the previous format?

Does anyone know if I should hope that this amazing module returns to its former glory?

**Comment by jessev14** [comment]
V12 update is in the works.
