### ISSUE TITLE
Use CSS for message styling

### ISSUE THREAD

**Issue by cs96and** [jessev14/dnd5e-character-monitor#5]
Currently the style of the monitor messages is set using inline styles...

![image](https://user-images.githubusercontent.com/898086/147857368-f2e70279-e5fd-41a0-909b-95640c950b2a.png)

It would be better if this was changed to use CSS, by applying custom classes to the messages instead.  This would mean that other modules could detect the monitor messages, and act accordingly.  The use case I am thinking of is [Chat Portrait](https://github.com/ShoyuVanilla/FoundryVTT-Chat-Portrait).  Currently, that modules applies portraits to the monitor messages, which bloats their size...

![image](https://user-images.githubusercontent.com/898086/147857411-81dac5c9-00dd-497e-ba06-d2f12850a953.png)

If the monitor messages used CSS, then Chat portrait could prevent the portrait appearing on monitor messages by using a `:not` selector.

**Comment by jessev14** [comment]
This module was developed under a commission, so I unfortunately don't have the time to make new functional updates. That said, I'm happy to review and merge PRs if you want to make the changes yourself. I can also implement the changes myself if funded.
