### ISSUE TITLE
HP and money tracking

### ISSUE THREAD

**Issue by ABrandau** [jessev14/dnd5e-character-monitor#7]
It might be outside the scope of the module, but i wonder if this request could be possible, players can change these two values on a whim and you can miss it at times.

**Comment by jessev14** [comment]
For HP tracking, I have another module to do that: https://github.com/jessev14/health-monitor

It would be possible to track gold. This module was developed on a commission, so unfortunately I don't have the means to work on it in my free time.
I'd be happy to merge a pull request if you can implement it yourself, or you can reach out to me on discord (`enso#0361`) if you want to discuss funding the update.

**Comment by jessev14** [comment]
The original commissioner of the module funded the option to monitor changes to gold as well. It is part of the `1.4.0` version release.
